# Generated by Django 5.2.5 on 2025-09-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': ' کاربران'},
        ),
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'verbose_name': 'کد تایید', 'verbose_name_plural': ' کد های تایید'},
        ),
    ]
